### ISSUE TITLE
Computable transitive closure of well-founded functions

### ISSUE THREAD

**Issue by eupp** [Event-Structures/event-struct#11]
- [x] Function that computes the list of predecessors of well-founded functions.
- [x] Define transitive closure using this function.
- [x] Prove spec of transitive closure.
- [ ] Extraction
- [x] Generalization to monads

**Comment by eupp** [comment]
Commit fae8989 partly addresses this issue. Let's move forward with other goals.

**Comment by dmitromikh** [comment]
@eupp, won't it be better first to refactor existing proofs?

**Comment by eupp** [comment]
> @eupp, won't it be better first to refactor existing proofs?

You can do refactorings first.
