### ISSUE TITLE
Silence warnings in a couple of Coq releases

### ISSUE THREAD

**Issue by anton-trunov** [Event-Structures/event-struct#42]
Coq 8.13 issues the following warnings as of commit 294771c1e504d73e05a4ab29ad8a966db5d57ae5:

1. Hint attributes

```
File "./utilities.v", line 140, characters 0-73:
Warning: The default value for hint locality is currently "local" in a
section and "global" otherwise, but is scheduled to change in a future
release. For the time being, adding hints outside of sections without
specifying an explicit locality is therefore deprecated. It is recommended to
use "export" whenever possible. [deprecated-hint-without-locality,deprecated]
```

To fix it, one needs to change line 140 into:

```coq
#[export] Hint Resolve trd_true3 snd_true3 snd_true2 frth_true4 fifth_true5 : core.
```

This only works starting from Coq **8.12**, i.e. we loose compatibility with Coq 8.11 if we fix this warning.

2. Boolean attributes syntax has been changed

```
File "./rfsfun.v", line 31, characters 0-22:
Warning:
Syntax for switching off boolean attributes has been updated, use canonical=no instead.
[deprecated-attribute-syntax,parsing]
```

One way to fix it is to change `#[canonical(false)]` into `#[canonical=no]`. This only work since Coq **8.13**.

**Comment by eupp** [comment]
> Coq 8.13 issues the following warnings as of commit [294771c](https://github.com/volodeyka/event-struct/commit/294771c1e504d73e05a4ab29ad8a966db5d57ae5):
> 
>     1. Hint attributes
> 
> 
> ```
> File "./utilities.v", line 140, characters 0-73:
> Warning: The default value for hint locality is currently "local" in a
> section and "global" otherwise, but is scheduled to change in a future
> release. For the time being, adding hints outside of sections without
> specifying an explicit locality is therefore deprecated. It is recommended to
> use "export" whenever possible. [deprecated-hint-without-locality,deprecated]
> ```
> 
> To fix it, one needs to change line 140 into:
> 
> ```coq
> #[export] Hint Resolve trd_true3 snd_true3 snd_true2 frth_true4 fifth_true5 : core.
> ```

What if we will specify the locality explicitly? Will it fix the warning message?
In general, I think it's good practice to specify the locality explicitly. Explicit is better than Implicit. 

> 
> This only works starting from Coq **8.12**, i.e. we loose compatibility with Coq 8.11 if we fix this warning.
> 
>     1. Boolean attributes syntax has been changed
> 
> 
> ```
> File "./rfsfun.v", line 31, characters 0-22:
> Warning:
> Syntax for switching off boolean attributes has been updated, use canonical=no instead.
> [deprecated-attribute-syntax,parsing]
> ```
> 
> One way to fix it is to change `#[canonical(false)]` into `#[canonical=no]`. This only work since Coq **8.13**.

Didn't the `canonical` attribute be introduced in the last releases? And then they have changed the syntax from `#[canonical(false)]` to `#[canonical=no]` almost immediately?
Wouldn't it be better then to just use the old trick with underscore `_`?
It also looks nicer in the source code, because `#[canonical]` attribute takes so much space.

The attribute and the identifier couldn't be placed on different lines, right?
```Coq
#[canonical=no]
foo : barType ...
```

**Comment by anton-trunov** [comment]
> What if we will specify the locality explicitly? Will it fix the warning message?

It will fix it but we need to do it in a backwards-compatible way. Hence the need to wait for a couple Coq releases (a common practice in this case).

> Explicit is better than Implicit.

Agreed! This is what this warning is all about.

> And then they have changed the syntax from #[canonical(false)] to #[canonical=no] almost immediately?

Sigh...

> The attribute and the identifier couldn't be placed on different lines, right?

Whitespace does not matter here, so this is exactly how I usually place these annotations :) Btw, #56 fixes this part.

**Comment by eupp** [comment]
> > What if we will specify the locality explicitly? Will it fix the warning message?
> 
> It will fix it but we need to do it in a backwards-compatible way. Hence the need to wait for a couple Coq releases (a common practice in this case).
> 
> > Explicit is better than Implicit.
> 
> Agreed! This is what this warning is all about.
> 
> > And then they have changed the syntax from #[canonical(false)] to #[canonical=no] almost immediately?
> 
> Sigh...
> 
> > The attribute and the identifier couldn't be placed on different lines, right?
> 
> Whitespace does not matter here, so this is exactly how I usually place these annotations :) Btw, #56 fixes this part.

**Comment by eupp** [comment]
> > What if we will specify the locality explicitly? Will it fix the warning message?
> 
> It will fix it but we need to do it in a backwards-compatible way. Hence the need to wait for a couple Coq releases (a common practice in this case).

Okay, let's wait then. 
But once it'll be stable, we will need to get back to it and set the locality.
Based on what I've read in [docs](https://coq.inria.fr/distrib/current/refman/proofs/automatic-tactics/auto.html#creating-hints)
the best choice would be `export`. I think that we should not use `global` at all. What do you think?

> 
> > Explicit is better than Implicit.
> 
> Agreed! This is what this warning is all about.
> 
> > And then they have changed the syntax from #[canonical(false)] to #[canonical=no] almost immediately?
> 
> Sigh...
> 
> > The attribute and the identifier couldn't be placed on different lines, right?
> 
> Whitespace does not matter here, so this is exactly how I usually place these annotations :) Btw, #56 fixes this part.

Ok. So for now we should keep using `#[canonical(false)]` (and then eventually we'll switch to `#[canonical=no]`).

**Comment by anton-trunov** [comment]
> the best choice would be export. 

Yep, that's what the corresponding Coq warning suggests to do :)
